const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { PGlite } = require('@electric-sql/pglite');

test('all migrations apply; profile isolation and durable assistant limits hold', async () => {
    const db = new PGlite();
    try {
        await db.exec(`
            create role anon; create role authenticated; create role service_role;
            create schema auth;
            create table auth.users (id uuid primary key, raw_user_meta_data jsonb);
            create function auth.uid() returns uuid language sql stable as
                $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
            grant usage on schema auth to authenticated, anon;
            grant execute on function auth.uid() to authenticated, anon;
            create schema storage;
            create table storage.buckets (id text primary key, name text, public boolean, file_size_limit bigint, allowed_mime_types text[]);
            create table storage.objects (name text, bucket_id text);
            alter table storage.objects enable row level security;
            create function storage.foldername(text) returns text[] language sql as $$ select string_to_array($1, '/') $$;
        `);
        for (const file of fs.readdirSync('supabase/migrations').filter((name) => name.endsWith('.sql')).sort()) {
            await db.exec(fs.readFileSync('supabase/migrations/' + file, 'utf8'));
        }
        const permissions = await db.query("select has_function_privilege('anon', 'public.handle_new_user()', 'execute') as anon_trigger, has_function_privilege('authenticated', 'public.handle_new_user()', 'execute') as authenticated_trigger, has_function_privilege('anon', 'public.record_daily_login_streak()', 'execute') as anon_streak, has_function_privilege('authenticated', 'public.record_daily_login_streak()', 'execute') as authenticated_streak");
        assert.deepEqual(permissions.rows[0], { anon_trigger: false, authenticated_trigger: false, anon_streak: false, authenticated_streak: true });
        const first = '00000000-0000-0000-0000-000000000001';
        const second = '00000000-0000-0000-0000-000000000002';
        await db.query('insert into auth.users values ($1, $3), ($2, $3)', [first, second, '{"display_name":"User"}']);
        await db.exec('set role authenticated');
        await db.query("select set_config('request.jwt.claim.sub', $1, false)", [first]);
        const profiles = await db.query('select id, assistant_mood, assistant_active_voice_ids from public.profiles');
        assert.equal(profiles.rows.length, 1);
        assert.equal(profiles.rows[0].id, first);
        assert.equal(profiles.rows[0].assistant_mood, 'balanced');
        const change = await db.query("update public.profiles set display_name = 'Other' where id = $1 returning id", [second]);
        assert.equal(change.rows.length, 0);
        await assert.rejects(db.exec('update public.profiles set daily_login_streak_count = 100'));
        await assert.rejects(db.exec('select * from public.assistant_usage'));
        const task = '10000000-0000-0000-0000-000000000001';
        await db.query("insert into public.tasks(id, title) values ($1, 'My task')", [task]);
        await assert.rejects(db.query("insert into public.tasks(user_id, title) values ($1, 'Foreign task')", [second]));
        await db.query("update public.tasks set status = 'done', priority = 'high' where id = $1", [task]);
        assert.equal((await db.query('select status from public.tasks where id = $1', [task])).rows[0].status, 'done');
        await assert.rejects(db.query('update public.tasks set user_id = $1 where id = $2', [second, task]));
        await db.query("select set_config('request.jwt.claim.sub', $1, false)", [second]);
        assert.equal((await db.query('select * from public.tasks')).rows.length, 0);
        assert.equal((await db.query("update public.tasks set title = 'Attack' where id = $1 returning id", [task])).rows.length, 0);
        assert.equal((await db.query('delete from public.tasks where id = $1 returning id', [task])).rows.length, 0);
        await db.query("select set_config('request.jwt.claim.sub', $1, false)", [first]);
        await db.query("insert into public.tasks(id, title) values ($1, 'Retry') on conflict(id) do nothing", [task]);
        assert.equal((await db.query('select title from public.tasks')).rows[0].title, 'My task');
        await assert.rejects(db.exec("insert into public.tasks(title) values ('')"));
        const project = '20000000-0000-0000-0000-000000000001';
        const foreignProject = '20000000-0000-0000-0000-000000000002';
        await db.query("insert into public.projects(id, name, start_date, due_date) values ($1, 'My project', '2026-10-01', '2026-10-10')", [project]);
        await db.query('update public.tasks set project_id = $1 where id = $2', [project, task]);
        assert.equal((await db.query('select project_id from public.tasks where id = $1', [task])).rows[0].project_id, project);
        await db.query("update public.projects set status = 'archived' where id = $1", [project]);
        assert.equal((await db.query('select count(*)::int as total from public.tasks where project_id = $1', [project])).rows[0].total, 1);
        await db.query("update public.projects set status = 'active' where id = $1", [project]);
        await assert.rejects(db.query("update public.projects set due_date = '2026-09-01' where id = $1", [project]));
        await assert.rejects(db.query('update public.projects set user_id = $1 where id = $2', [second, project]));
        await db.query("select set_config('request.jwt.claim.sub', $1, false)", [second]);
        assert.equal((await db.query('select id from public.projects')).rows.length, 0);
        await db.query("insert into public.projects(id, name) values ($1, 'Second project')", [foreignProject]);
        assert.equal((await db.query("update public.projects set name = 'Attack' where id = $1 returning id", [project])).rows.length, 0);
        await assert.rejects(db.query("insert into public.tasks(title, project_id) values ('Foreign association', $1)", [project]));
        await db.query("select set_config('request.jwt.claim.sub', $1, false)", [first]);
        await assert.rejects(db.query('update public.tasks set project_id = $1 where id = $2', [foreignProject, task]));
        await db.query('update public.tasks set project_id = null where id = $1', [task]);
        assert.equal((await db.query('select project_id from public.tasks where id = $1', [task])).rows[0].project_id, null);
        const focus = '30000000-0000-0000-0000-000000000001';
        const focus2 = '30000000-0000-0000-0000-000000000002';
        const startFocus = async (sessionId, taskId = task, kind = 'work', minutes = 25) =>
            (await db.query('select to_jsonb(public.start_focus_session($1, $2, $3, $4, $5)) as session', [sessionId, taskId, 'Focus', kind, minutes])).rows[0].session;
        const transition = async (sessionId, action, version) =>
            (await db.query('select to_jsonb(public.transition_focus_session($1, $2, $3)) as session', [sessionId, action, version])).rows[0].session;
        const backdate = async (seconds) => {
            await db.exec('reset role');
            await db.query("update public.focus_sessions set running_since = clock_timestamp() - make_interval(secs => $1) where id = $2", [seconds, focus]);
            await db.exec('set role authenticated');
        };
        const started = await startFocus(focus);
        assert.equal(started.task_id, task);
        assert.equal(started.label, 'My task');
        assert.equal((await startFocus(focus)).id, focus);
        assert.equal((await db.query('select * from public.focus_sessions')).rows.length, 1);
        await assert.rejects(startFocus(focus2), /active session/);
        await assert.rejects(db.query('update public.focus_sessions set elapsed_seconds = 100 where id = $1', [focus]));
        await assert.rejects(db.query("insert into public.focus_sessions(id, user_id, label, kind, planned_seconds) values ($1, $2, 'Fake', 'work', 1500)", [focus2, first]));
        await assert.rejects(db.query('delete from public.focus_sessions where id = $1', [focus]));
        await db.query("select set_config('request.jwt.claim.sub', $1, false)", [second]);
        assert.equal((await db.query('select * from public.focus_sessions')).rows.length, 0);
        await assert.rejects(transition(focus, 'finish', 0), /unavailable/);
        await assert.rejects(startFocus(focus2, task), /available task/);
        await db.query("select set_config('request.jwt.claim.sub', $1, false)", [first]);
        await backdate(120);
        const paused = await transition(focus, 'pause', 0);
        assert.equal(paused.elapsed_seconds, 120);
        assert.equal(paused.running_since, null);
        await assert.rejects(transition(focus, 'finish', 0), /another tab/);
        await assert.rejects(transition(focus, 'pause', 1), /Invalid session transition/);
        const resumed = await transition(focus, 'resume', 1);
        assert.equal(resumed.elapsed_seconds, 120);
        await backdate(60);
        const finished = await transition(focus, 'finish', 2);
        assert.equal(finished.elapsed_seconds, 180);
        assert.equal(finished.status, 'completed');
        assert.deepEqual(await transition(focus, 'finish', 2), finished);
        await assert.rejects(transition(focus, 'resume', 3), /already ended/);
        // Completed work follows the original task when it moves to another project.
        await db.query('update public.tasks set project_id = $1 where id = $2', [project, task]);
        assert.equal((await db.query("select sum(f.elapsed_seconds)::int as actual from public.focus_sessions f join public.tasks t on t.id = f.task_id where t.project_id = $1 and f.status = 'completed' and f.kind = 'work'", [project])).rows[0].actual, 180);
        await assert.rejects(startFocus(focus2, null, 'work', 0), /Invalid focus/);
        await assert.rejects(startFocus(focus2, task, 'break', 5), /Breaks cannot/);
        await startFocus(focus2, null, 'break', 5);
        const cancelled = await transition(focus2, 'cancel', 0);
        assert.equal(cancelled.status, 'cancelled');
        assert.deepEqual(await transition(focus2, 'cancel', 0), cancelled);
        const focus3 = '30000000-0000-0000-0000-000000000003';
        await startFocus(focus3, null, 'work', 1);
        await db.exec('reset role');
        await db.query("update public.focus_sessions set running_since = clock_timestamp() - interval '2 hours' where id = $1", [focus3]);
        await db.exec('set role authenticated');
        assert.equal((await transition(focus3, 'finish', 0)).elapsed_seconds, 60);
        const focus4 = '30000000-0000-0000-0000-000000000004';
        await startFocus(focus4, task);
        await db.query('delete from public.tasks where id = $1', [task]);
        assert.equal((await db.query('select task_id from public.focus_sessions where id = $1', [focus])).rows[0].task_id, null);
        assert.equal((await transition(focus4, 'finish', 0)).task_id, null);
        assert.equal((await db.query('select elapsed_seconds from public.focus_sessions where id = $1', [focus])).rows[0].elapsed_seconds, 180);
        await db.query("select set_config('request.jwt.claim.sub', '', false)");
        await assert.rejects(startFocus(focus2), /Sign in/);
        await assert.rejects(transition(focus, 'finish', 0), /Sign in/);
        await db.exec('set role anon');
        await assert.rejects(startFocus(focus2));
        await assert.rejects(transition(focus, 'finish', 0));
        await assert.rejects(db.exec('select * from public.focus_sessions'));
        await db.exec('set role authenticated');
        await db.query("select set_config('request.jwt.claim.sub', $1, false)", [first]);
        const consume = async (channel) => (await db.query('select public.consume_assistant_allowance($1) as allowed', [channel])).rows[0].allowed;
        for (let i = 0; i < 10; i++) assert.equal(await consume('chat'), true);
        assert.equal(await consume('chat'), false);
        assert.equal(await consume('voice'), true);
        assert.equal(await consume('invalid'), false);
        await db.query("select set_config('request.jwt.claim.sub', $1, false)", [second]);
        assert.equal(await consume('chat'), true);
        await db.exec('reset role');
        await db.query("update public.assistant_usage set minute_start = now() - interval '2 minutes' where user_id = $1", [first]);
        await db.exec('set role authenticated');
        await db.query("select set_config('request.jwt.claim.sub', $1, false)", [first]);
        assert.equal(await consume('chat'), true);
        await db.exec('reset role');
        await db.query("update public.assistant_usage set day_count = 100, minute_start = now() - interval '2 minutes' where user_id = $1", [first]);
        await db.exec('set role authenticated');
        assert.equal(await consume('chat'), false);
        await db.exec('reset role');
        await db.query("update public.assistant_usage set day_start = current_date - 1 where user_id = $1", [first]);
        await db.exec('set role authenticated');
        assert.equal(await consume('chat'), true);
        await db.query("select set_config('request.jwt.claim.sub', '', false)");
        assert.equal(await consume('chat'), false);
        await db.exec('set role anon');
        await assert.rejects(consume('chat'));
    } finally { await db.close(); }
});
