const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');
test('daily planning enforces hierarchy, ownership, revisions, scheduling and immutable history',async()=>{
 const db=new PGlite();const owner='00000000-0000-0000-0000-000000000001',other='00000000-0000-0000-0000-000000000002';
 const parent='10000000-0000-0000-0000-000000000001',child1='10000000-0000-0000-0000-000000000002',child2='10000000-0000-0000-0000-000000000003';
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,raw_user_meta_data jsonb);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
 create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(name text,bucket_id text);alter table storage.objects enable row level security;
 create function storage.foldername(text) returns text[] language sql as $$ select string_to_array($1,'/') $$;`);
 for(const file of fs.readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));
 await db.query("insert into auth.users values($1,'{}'),($2,'{}')",[owner,other]);
 await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
 await db.query("insert into public.tasks(id,title,estimated_minutes) values($1,'Parent',90)",[parent]);
 const children=[{id:child1,title:'First step',description:'',estimatedMinutes:20},{id:child2,title:'Second step',description:'',estimatedMinutes:30}];
 await db.query('select public.split_task($1,$2)',[parent,JSON.stringify(children)]);
 await db.query('select public.split_task($1,$2)',[parent,JSON.stringify(children)]);
 assert.equal((await db.query('select count(*)::int as count from public.tasks')).rows[0].count,3);
 assert.equal((await db.query('select estimated_minutes from public.tasks where id=$1',[parent])).rows[0].estimated_minutes,50);
 await assert.rejects(db.query("update public.tasks set status='done' where id=$1",[parent]),/subtasks/);
 await db.query("update public.tasks set status='done' where parent_id=$1",[parent]);
 assert.equal((await db.query('select status from public.tasks where id=$1',[parent])).rows[0].status,'ready_for_review');
 await db.query("update public.tasks set status='done' where id=$1",[parent]);
 await db.query("update public.tasks set status='todo' where id=$1",[child1]);
 assert.equal((await db.query('select status from public.tasks where id=$1',[parent])).rows[0].status,'in_progress');
 await db.query('update public.tasks set estimated_minutes=null where id=$1',[child2]);
 assert.deepEqual((await db.query('select public.task_estimate_snapshot($1) as value',[parent])).rows[0].value,{minutes:20,unknown:1});
 await assert.rejects(db.query("insert into public.tasks(title,parent_id) values('Nested',$1)",[child1]),/top-level/);
 const today=(await db.query('select current_date::text as day')).rows[0].day;
 const items=[{taskId:child1,start:today+'T12:00:00Z',end:today+'T12:30:00Z',title:'Forged',status:'done'}];
 await db.query('select public.save_daily_plan($1,$2,$3,$4,$5)',[today,'UTC',45,JSON.stringify(items),0]);
 let plan=(await db.query('select * from public.daily_plans')).rows[0];
 assert.equal(plan.items[0].title,'First step');assert.equal(plan.items[0].status,'todo');assert.equal(plan.items[0].estimate.minutes,20);
 await assert.rejects(db.query('select public.save_daily_plan($1,$2,$3,$4,$5)',[today,'UTC',45,JSON.stringify(items),0]),/changed/);
 await assert.rejects(db.query('select public.save_daily_plan($1,$2,$3,$4,$5)',[today,'UTC',45,JSON.stringify([{taskId:parent,start:null,end:null},...items]),plan.revision]),/parent or its subtasks/);
 await assert.rejects(db.query('select public.save_daily_plan($1,$2,$3,$4,$5)',[today,'UTC',45,JSON.stringify([{taskId:child1,start:today+'T14:00:00Z',end:today+'T13:00:00Z'}]),plan.revision]),/valid work block/);
 await db.query("update public.tasks set title='Renamed',estimated_minutes=25,status='done' where id=$1",[child1]);
 plan=(await db.query('select * from public.daily_plans')).rows[0];
 assert.equal(plan.items[0].title,'Renamed');assert.equal(plan.items[0].status,'done');assert.equal(plan.items[0].estimate.minutes,25);
 await db.exec('reset role;alter table public.daily_plans disable trigger guard_daily_plan;update public.daily_plans set plan_date=current_date-1;alter table public.daily_plans enable trigger guard_daily_plan;set role authenticated');
 const historical=JSON.stringify((await db.query('select items from public.daily_plans')).rows[0].items);
 await db.query("update public.tasks set title='Later edit',status='todo' where id=$1",[child1]);
 assert.equal(JSON.stringify((await db.query('select items from public.daily_plans')).rows[0].items),historical);
 await assert.rejects(db.exec('update public.daily_plans set budget_minutes=100'),/read-only/);
 const project='20000000-0000-0000-0000-000000000001';
 await db.query("insert into public.projects(id,name) values($1,'Connected project')",[project]);
 await db.query('update public.tasks set project_id=$1 where id=$2',[project,parent]);
 assert.equal((await db.query('select project_id from public.tasks where id=$1',[child1])).rows[0].project_id,project);
 await db.query("update public.projects set status='archived' where id=$1",[project]);
 assert.equal((await db.query('select count(*)::int as count from public.tasks where archived_at is not null')).rows[0].count,3);
 await assert.rejects(db.query('update public.tasks set archived_at=null where id=$1',[parent]),/Restore the project/);
 await db.query("update public.projects set status='active' where id=$1",[project]);
 await db.query('update public.tasks set archived_at=null where id=$1',[parent]);
 assert.equal((await db.query('select count(*)::int as count from public.tasks where archived_at is not null')).rows[0].count,0);
 await assert.rejects(db.exec("insert into public.planning_settings(timezone) values('Invalid/Zone')"),/timezone/);
 await db.query("insert into public.planning_settings(user_id,timezone) values($1,'UTC') on conflict(user_id) do nothing",[owner]);
 await db.query("insert into public.planning_settings(user_id,timezone) values($1,'America/New_York') on conflict(user_id) do nothing",[owner]);
 await db.query("update public.planning_settings set timezone='America/New_York' where user_id=$1",[owner]);
 assert.equal((await db.query('select timezone from public.planning_settings')).rows[0].timezone,'America/New_York');
 await assert.rejects(db.query('update public.planning_settings set user_id=$1',[other]));
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[other]);
 assert.equal((await db.query('select * from public.daily_plans')).rows.length,0);
 assert.equal((await db.query('select * from public.tasks')).rows.length,0);
 await assert.rejects(db.query('select public.split_task($1,$2)',[parent,JSON.stringify(children)]),/top-level/);
 await assert.rejects(db.query('select public.save_daily_plan($1,$2,$3,$4,$5)',[today,'UTC',30,JSON.stringify(items),0]),/unavailable/);
 await db.exec('set role anon');await assert.rejects(db.exec('select * from public.daily_plans'));await assert.rejects(db.query('select public.split_task($1,$2)',[parent,JSON.stringify(children)]));
 }finally{await db.close();}
});
